name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag magic-launcher:latest

    - name: Do a quick run of the image and confirm files are present
      run: |
        docker run --rm magic-launcher:latest ls -la /home/magicuser/.local/share/Magic-Launcher
        docker run --rm magic-launcher:latest cat "/home/magicuser/.local/share/Magic-Launcher/launcher/__init__.py" && exit 0 || exit 1
