name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag magic-launcher:latest

    - name: Do a quick run of the image and confirm files are present
      run: |
        docker run --rm magic-launcher:latest ls -la /app
        docker run --rm magic-launcher:latest python3 -c "import launcher; print(launcher.__version__)" && exit 0 || exit 1
